### create new user
POST http://localhost:3000/api/v1/auth/register

{
  "name": "sandi",
  "email": "sandi@something.com",
  "password": "123456"
}

### cek login user
POST http://localhost:3000/api/v1/auth/login

{
  "email": "sandi@something.com",
  "password": "123456"
}